[project]
name = "Reverse Search"
version = "0.1.0"
description = "Reverse search endpoints for various providers."
requires-python = ">=3.13"
dependencies = [
    "aiohttp",
	"workers-py",
]

[dependency-groups]
dev = [
	"workers-py",
	"workers-runtime-sdk"
]